DELETE FROM warehouse.fact_deliverable_snapshot
WHERE load_batch_id = %(load_batch_id)s;

INSERT INTO warehouse.fact_deliverable_snapshot (
    raw_row_id,
    load_batch_id,
    source_row_num,
    deliverable_id,
    deliverable_type,
    supplement_type,
    reference,
    title_en,
    title_fr,
    publication_date,
    publication_year,
    edition,
    owner_committee,
    current_stage_raw,
    current_stage_code,
    stage_family_code,
    stage_subcode,
    is_published,
    is_withdrawn,
    has_title_en,
    has_title_fr,
    pages_en,
    scope_en_html,
    scope_en_text,
    source_file,
    ingested_at
)
SELECT
    raw_row_id,
    load_batch_id,
    source_row_num,
    deliverable_id,
    deliverable_type,
    supplement_type,
    reference,
    title_en,
    title_fr,
    publication_date,
    publication_year,
    edition,
    owner_committee,
    current_stage_raw,
    current_stage_code,
    stage_family_code,
    stage_subcode,
    is_published,
    is_withdrawn,
    has_title_en,
    has_title_fr,
    pages_en,
    scope_en_html,
    scope_en_text,
    source_file,
    ingested_at
FROM staging.iso_deliverables_clean
WHERE load_batch_id = %(load_batch_id)s;
